# Папки
input_dir: ./test_images              # где слушаем .pic
output_dir: ./results
test_mode: true             # или false
test_images_dir: ./test_images    # папка с тестовыми изображениями    
camera_matrix:
  - [8049.984331021995, 0.0, 1470.9594033192748]
  - [0.0, 8031.233316708024, 1172.2674105508036]
  - [0.0, 0.0, 1.0]
dist_coefs:
  [ -0.37989819778815725,
     0.7637840078410085,
    -0.014302099675147666,
     0.013396845602165934,
    -7.11612361852026 ]
perspective_points:
  TL: [349, 244]
  BL: [438, 1682]
  TR: [3638, 312]
  BR: [3502, 1756]
real_width: 283.0    # см
real_height: 138.0 # см

# ONNX → TensorRT
onnx_path:        ./mask_rcnn_r50fpn3x_1333_800_bs1.onnx
engine_path:      ./mask_rcnn_r50fpn3x_1333_800_bs1.trt
max_workspace_size: 1073741824  # в байтах (1 GiB)
fp16:             true         # true для FP16


# Инференс
input_shape:     [3, 800, 1333]  # [C, H, W]
debug:            true         # сохранять overlay-картинки
debug_output:     ./debug      # папка для debug-изображений
overlay_color:    [0, 255, 0]  # цвет маски BGR
