# Папки
input_dir: /va104              # где слушаем .pic
output_dir: ./results
test_mode: true             # или false
test_images_dir: ./test_def    # папка с тестовыми изображениями    

# Общинге настройки
device: 0                 # GPU ID
debug: true               # сохранять overlay *.jpg

# Препроцесснг
camera_matrix:
  - [8049.984331021995, 0.0, 1470.9594033192748]
  - [0.0, 8031.233316708024, 1172.2674105508036]
  - [0.0, 0.0, 1.0]
dist_coefs:
  [ -0.37989819778815725,
     0.7637840078410085,
    -0.014302099675147666,
     0.013396845602165934,
    -7.11612361852026 ]
perspective_points:
  # TL: [346, 300]
  # BL: [428, 1680]
  # TR: [3633, 377]
  # BR: [3501, 1756]

  # TL: [327, 236]
  # BL: [414, 1657]
  # TR: [3638, 302]
  # BR: [3501, 1745]
  TL: [357, 252]
  BL: [444, 1657]
  TR: [3604, 313]
  BR: [3469, 1741]
real_width: 283.0    # см
real_height: 138.0 # см


models:
  profile:
    onnx_model: ./weights/yolo8l_seg_1024_220525.onnx
    num_classes: 1
    conf_thres: 0.7
    iou_thres: 0.5
    imgsz: 1024
    combine: best
  defect:
    onnx_model: ./weights/yolo8l_seg_def_1024_280525.onnx
    num_classes: 2
    conf_thres: 0.25
    iou_thres: 0.4
    imgsz: 1024
    combine: all

# отрисовка метрик
font_scale: 1.7
font_thickness: 3
overlay_color: [0, 0, 0]

width_threshold: 0.98          # T из шага 2 (0.8 = 80 %)
color_first:  [0, 255, 0]     # BGR-цвет 1-го сорта
color_second: [0, 200, 255]   # BGR-цвет 2-го сорта (оранжевый)

defect_classes:
  0: {name: Переход. деф,  color: [255,   0,   0]}   # красный
  1: {name: Трещины, color: [  0, 0, 255]}   # оранжевый

panel_font_size: 50     
panel_width_px: 850