# Папки
input_dir: ./test_images              # где слушаем .pic
output_dir: ./results
test_mode: true             # или false
test_images_dir: ./test    # папка с тестовыми изображениями    

# Препроцесснг
camera_matrix:
  - [8049.984331021995, 0.0, 1470.9594033192748]
  - [0.0, 8031.233316708024, 1172.2674105508036]
  - [0.0, 0.0, 1.0]
dist_coefs:
  [ -0.37989819778815725,
     0.7637840078410085,
    -0.014302099675147666,
     0.013396845602165934,
    -7.11612361852026 ]
perspective_points:
  TL: [177, 494]
  BL: [285, 1716]
  TR: [3073, 482]
  BR: [2993, 1699]
real_width: 283.0    # см
real_height: 138.0 # см

# onnx-инференс
onnx_model: ./weights/yolo8l_seg_1024_220525.onnx
imgsz: 1024
conf_thres: 0.7
iou_thres: 0.5
device: 0                 # GPU ID
debug: true               # сохранять overlay *.jpg

# отрисовка метрик
font_scale: 1.5
font_thickness: 3
overlay_color: [0, 0, 0]

width_threshold: 0.95          # T из шага 2 (0.8 = 80 %)
color_first:  [0, 255, 0]     # BGR-цвет 1-го сорта
color_second: [0, 200, 255]   # BGR-цвет 2-го сорта (оранжевый)
