services:
  profiler:
    restart: always
    build:
      context: .
      network: host
    # ── GPU ──────────────────────────────────────────────
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia        # nvidia-ctk прописал runtime
              count: all            # можно 1,2… или all
              capabilities: [gpu]   # compute + utility по умолчанию
    # ── тома ────────────────────────────────────────────
    volumes:
      - ./:/app/
      - /va104:/va104
      - /home/egida-va/results:/results/